// Abstract this later
var jsondata = [{
  "restaurant": "Tougo Coffee",
  "neighborhood": "3 locations",
  "address": "1410 18th Ave, Seattle, WA 98122",
  "lat": "47.61326",
  "long": "-122.30869",
  "service": "Takeout",
  "contact": "(206) 467-5042",
  "website": "https://www.tougocoffee.com/",
  "type": "Coffee",
  "MERCH/ONLINE STORE": "Coffee - get Tougo Coffee at Yesler Terrace Cafe.",
  "EMAIL CONTACT": "Infofh@tougocoffee.com"
},
{
  "restaurant": "Tougo Coffee",
  "address": "800 Convention Pl, Seattle, WA 98101",
  "lat": "47.611498",
  "long": "-122.33158",
  "service": "Takeout",
  "contact": "(206) 467-5042",
  "website": "https://www.tougocoffee.com/",
  "type": "Coffee"
},
{
  "restaurant": "Tougo Coffee",
  "address": "860 Yesler Way, Seattle, WA 98104",
  "lat": "47.601856",
  "long": "-122.32161",
  "service": "Takeout",
  "contact": "(206) 467-5042",
  "website": "https://www.tougocoffee.com/",
  "type": "Coffee"
},
{
  "restaurant": "Bantaba",
  "neighborhood": "Alderwood",
  "address": "19417 36th Ave W, Lynnwood, WA 98036",
  "lat": "47.822534",
  "long": "-122.28124",
  "service": "Takeout, Delivery",
  "contact": "(425) 678-0202",
  "website": "bantabarestaurant.com",
  "EMAIL CONTACT": "TBD"
},
{
  "restaurant": "Trotter's Restaurant",
  "neighborhood": "Auburn",
  "address": "825 Harvey Rd NE, Auburn, WA 98002",
  "lat": "47.31566",
  "long": "-122.2153",
  "service": "Takeout",
  "contact": "(253) 833-2323",
  "website": "https://www.trottersfamilyrestaurant.com/",
  "EMAIL CONTACT": "trotters825@yahoo.com"
},
{
  "restaurant": "SoSo Good Food Truck",
  "neighborhood": "Ballard",
  "address": "2217 NW Market St #21, Seattle, WA 98107",
  "lat": "47.668519",
  "long": "-122.38552",
  "service": "Takeout",
  "contact": "(480) 290-8493",
  "website": "https://www.facebook.com/eatsosogood/",
  "OTHER": "Food truck!",
  "EMAIL CONTACT": "eatsosogood@gmail.com"
},
{
  "restaurant": "Tre's House of Cheesesteaks",
  "neighborhood": "Ballard",
  "address": "4300 Leary Way NW Seattle, Washington 98107",
  "lat": "47.659112",
  "long": "-122.36452",
  "service": "Takeout",
  "contact": "thoc08@yahoo.com",
  "website": "https://www.facebook.com/Treshouseofcheesesteaks/",
  "OTHER": "Apparently these cheesesteaks are incredible! Someone LMK!",
  "EMAIL CONTACT": "thoc08@yahoo.com"
},
{
  "restaurant": "The Station",
  "neighborhood": "Beacon Hill",
  "address": "1600 S Roberto Maestas Festival St, Seattle, WA 98144",
  "lat": "47.579599",
  "long": "-122.31188",
  "service": "Takeout, Delivery",
  "contact": "(206) 271-7302",
  "website": "https://www.thestationbh.com/",
  "MERCH/ONLINE STORE": "Coffee, wine, sandwiches and more",
  "EMAIL CONTACT": "thestationcoffeeshop@gmail.com"
},
{
  "restaurant": "The Comfort Zone",
  "neighborhood": "Beacon Hill",
  "address": "5016 Rainier Ave S, Seattle, WA 98118",
  "lat": "47.556551",
  "long": "-122.28378",
  "service": "Takeout, Delivery",
  "contact": "(206) 246-2800",
  "website": "https://thecomfortzonesoulfood.com/",
  "MERCH/ONLINE STORE": "Catering available.",
  "EMAIL CONTACT": "hello@thecomfortzonesoulfood.com"
},
{
  "restaurant": "Amy's Merkato",
  "neighborhood": "Beacon Hill",
  "address": "5706 Rainier Ave S, Seattle, WA 98118",
  "lat": "47.55102",
  "long": "-122.27737",
  "service": "Takeout",
  "contact": "(206) 324-2527",
  "website": "https://amyscafeseattle.com/",
  "MERCH/ONLINE STORE": "Order food or purchase groceries (spices, coffee, injera) from their stores.",
  "OTHER": "Gift certificates available.",
  "EMAIL CONTACT": "TBD"
},
{
  "restaurant": "The Original Phillys",
  "neighborhood": "Beacon Hill",
  "address": "3019 Martin Luther King Jr Way S, Seattle, WA 98144",
  "lat": "47.576228",
  "long": "-122.29704",
  "service": "Takeout",
  "contact": "(206) 723-7445",
  "website": "http://theoriginalphillysseattle3.cafecityguide.website/",
  "EMAIL CONTACT": "theoriginalphillys@gmail.com"
},
{
  "restaurant": "Monona Cafe and Restaurant",
  "neighborhood": "Beacon Hill",
  "address": "6754 Martin Luther King Jr Way S, Seattle, WA 98118",
  "lat": "47.540979",
  "long": "-122.28273",
  "service": "Takeout",
  "contact": "(206) 766-0607",
  "website": "http://mononacafeandrestaurantseattle.cafecityguide.website/",
  "EMAIL CONTACT": "TBD"
},
{
  "restaurant": "Baked from the Hart",
  "neighborhood": "Beacon Hill",
  "address": "2801 S Hanford St, Seattle, WA 98144",
  "lat": "47.574477",
  "long": "-122.29642",
  "service": "Takeout",
  "contact": "(206) 650-9191",
  "website": "https://bakedfromthehart.com/",
  "type": "Bakery",
  "MERCH/ONLINE STORE": "CUTEST BAKERY. He's been baking for over 50 years.",
  "OTHER": "Bakedfromthehart@gmail.com"
},
{
  "restaurant": "Cafe Campagne",
  "neighborhood": "Belltown",
  "address": "1600 Post Alley, Seattle, WA 98101",
  "lat": "47.609746",
  "long": "-122.34143",
  "service": "Takeout, Delivery",
  "contact": "(206) 728-2233",
  "website": "https://cafecampagne.com/",
  "EMAIL CONTACT": "edavid@cafecampagne.com"
},
{
  "restaurant": "Jerk Shack",
  "neighborhood": "Belltown",
  "address": "2512 1st Ave, Seattle, WA 98121",
  "lat": "47.615138",
  "long": "-122.34917",
  "service": "Takeout, Delivery",
  "contact": "(206) 441-7817",
  "website": "https://jerkshackseattle.com/",
  "MERCH/ONLINE STORE": "Catering available.",
  "EMAIL CONTACT": "jerkshackseattle@gmail.com"
},
{
  "restaurant": "Carolina Smoke",
  "neighborhood": "Bothell",
  "address": "24118 Bothell Everett Hwy, Bothell, WA 98021",
  "lat": "47.778698",
  "long": "-122.21878",
  "service": "Takeout",
  "contact": "(425) 949-8672",
  "website": "carolinasmoke.com",
  "MERCH/ONLINE STORE": "Incredible. Cornbread. Seriously.",
  "EMAIL CONTACT": "info@carolinasmoke.com"
},
{
  "restaurant": "Classic Eats",
  "neighborhood": "Burien",
  "address": "918 SW 152nd St, Burien, WA 98166",
  "lat": "47.466888",
  "long": "-122.34651",
  "service": "Takeout",
  "contact": "(206) 241-6275",
  "website": "classiceatsburien.com",
  "MERCH/ONLINE STORE": "Meal prep and catering available.",
  "EMAIL CONTACT": "classiceats@yahoo.com"
},
{
  "restaurant": "Plum Bistro",
  "neighborhood": "Capitol Hill",
  "address": "1429 12th Ave, Seattle, WA 98122",
  "lat": "47.613815",
  "long": "-122.3171",
  "service": "Takeout, Delivery",
  "contact": "(206) 838-5333",
  "website": "https://plumbistro.com/",
  "MERCH/ONLINE STORE": "Yes - check out their website.",
  "OTHER": "All vegan restaurant.",
  "EMAIL CONTACT": "info@plumbistro.com"
},
{
  "restaurant": "Cafe Soleil",
  "neighborhood": "Capitol Hill",
  "address": "3406 E Union St, Seattle, WA 98122",
  "lat": "47.612996",
  "long": "-122.28888",
  "service": "Takeout",
  "contact": "206) 325-1126",
  "website": "https://www.thestranger.com/seattle/cafe-soleil/Content?oid=15158",
  "EMAIL CONTACT": "CafeSoleil@comcast.net"
},
{
  "restaurant": "Simply Soulful",
  "neighborhood": "Capitol Hill",
  "address": "2915 E Madison St, Seattle, WA 98112",
  "lat": "47.624113",
  "long": "-122.29493",
  "service": "Takeout",
  "contact": "(206) 474-9841",
  "website": "https://www.simplysoulfulcafe.com/",
  "MERCH/ONLINE STORE": "Catering available.",
  "EMAIL CONTACT": "lrambus@gmail.com"
},
{
  "restaurant": "Marjorie Restaurant",
  "neighborhood": "Capitol Hill",
  "address": "1412 E Union St, Seattle, WA 98122",
  "lat": "47.613163",
  "long": "-122.31352",
  "service": "Takeout",
  "contact": "(206) 441-9842",
  "website": "https://marjorierestaurant.com/",
  "MERCH/ONLINE STORE": "Plantains, tees, and big meal preps available.",
  "OTHER": "Gift certificates available.",
  "EMAIL CONTACT": "info@marjorierestaurant.com"
},
{
  "restaurant": "Poco Wine + Spirits",
  "neighborhood": "Capitol Hill",
  "address": "1408 E Pine St, Seattle, WA 98122",
  "lat": "47.61543",
  "long": "-122.31372",
  "service": "Takeout",
  "contact": "(206) 322-9463",
  "website": "http://www.pocowineandspirits.com/",
  "MERCH/ONLINE STORE": "Wine and bites.",
  "EMAIL CONTACT": "info@pocowineandspirits.com"
},
{
  "restaurant": "Queen Sheba Ethiopian Restaurant",
  "neighborhood": "Capitol Hill",
  "address": "916 E John St, Seattle, WA 98102",
  "lat": "47.620062",
  "long": "-122.32013",
  "service": "Takeout",
  "contact": "(206) 322-0852",
  "website": "http://ethiopianrestaurantseattle.com/",
  "EMAIL CONTACT": "info@queenshebaeattle.com"
},
{
  "restaurant": "Osteria la Spiga",
  "neighborhood": "Capitol Hill",
  "address": "1429 12th Ave, Seattle, WA 98122",
  "lat": "47.613815",
  "long": "-122.3171",
  "service": "Takeout",
  "contact": "(206) 323-8881",
  "website": "laspiga.com",
  "MERCH/ONLINE STORE": "Order dinner or purchase bulk foods (frozen pasta, lasagna trays, signature sauces, wine & other goodies) from their store.",
  "EMAIL CONTACT": "hello@laspiga.com"
},
{
  "restaurant": "Footprint Wine Tap",
  "neighborhood": "Capitol Hill",
  "address": "1222 E Madison St, Seattle, WA 98122",
  "lat": "47.613507",
  "long": "-122.31591",
  "service": "Takeout",
  "contact": "(206) 485-7175",
  "website": "https://footprintwine.com/",
  "MERCH/ONLINE STORE": "Wine! Membership and online orders available.",
  "EMAIL CONTACT": "info@footprintwine.com"
},
{
  "restaurant": "Wonder Bar",
  "neighborhood": "Central District",
  "address": "1800 S Jackson St, Seattle, WA 98144",
  "lat": "47.599668",
  "long": "-122.30841",
  "service": "Takeout, Delivery",
  "contact": "(206) 538-0044",
  "website": "wondersportbar.com",
  "MERCH/ONLINE STORE": "Yes - check out their website.",
  "EMAIL CONTACT": "TEFERIBI@yahoo.com"
},
{
  "restaurant": "Fat’s Chicken and Waffles",
  "neighborhood": "Central District",
  "address": "2726 E Cherry St, Seattle, WA 98122",
  "lat": "47.608146",
  "long": "-122.29647",
  "service": "Takeout, Delivery",
  "contact": "(206) 602-6863)",
  "website": "fatschickenandwaffles.com",
  "MERCH/ONLINE STORE": "Catering available.",
  "EMAIL CONTACT": "ewhite@fatschickenandwaffles.com"
},
{
  "restaurant": "Meskel",
  "neighborhood": "Central District",
  "address": "2605 E Cherry St, Seattle, WA 98122",
  "lat": "47.607805",
  "long": "-122.29856",
  "service": "Takeout",
  "contact": "(206) 860-1724",
  "website": "https://meskelethiopian.com/",
  "EMAIL CONTACT": "alemufam@gmail.com"
},
{
  "restaurant": "Cortona Cafe",
  "neighborhood": "Central District",
  "address": "2425 E Union St, Seattle, WA 98122",
  "lat": "47.61276",
  "long": "-122.30028",
  "service": "Takeout",
  "contact": "(206) 327-9728",
  "website": "http://cortonacafe.com/",
  "MERCH/ONLINE STORE": "Coffee and light food",
  "EMAIL CONTACT": "info@cortonacafe.com"
},
{
  "restaurant": "Central Cafe and Juice Bar",
  "neighborhood": "Central District",
  "address": "2514 E Cherry St, Seattle, WA 98122",
  "lat": "47.60819",
  "long": "-122.29941",
  "service": "Takeout, Delivery",
  "contact": "(206) 538-0380",
  "website": "https://www.centralcafeseattle.com/",
  "OTHER": "Eco-Conscious cafe",
  "EMAIL CONTACT": "TBD"
},
{
  "restaurant": "Cafe Selam",
  "neighborhood": "Central District",
  "address": "2715 E Cherry St, Seattle, WA 98122",
  "lat": "47.607793",
  "long": "-122.29707",
  "service": "Takeout",
  "contact": "(206) 328-0404",
  "website": "https://www.cafeselam.com/",
  "EMAIL CONTACT": "salama1998@gmail.com"
},
{
  "restaurant": "Adey Abeba",
  "neighborhood": "Central District",
  "address": "2123 E Union St, Seattle, WA 98122",
  "lat": "47.612741",
  "long": "-122.30384",
  "service": "Takeout",
  "contact": "(206) 322-1617",
  "website": "https://adeyabeba.net/",
  "MERCH/ONLINE STORE": "Catering available.",
  "EMAIL CONTACT": "TBD"
},
{
  "restaurant": "Nate's Wings and Waffles",
  "neighborhood": "Central District",
  "address": "1224 E Jefferson St, Seattle, WA 98122",
  "lat": "47.60633",
  "long": "-122.31564",
  "service": "Takeout, Delivery",
  "contact": "(206) 629-2051",
  "website": "https://natesww.com/",
  "MERCH/ONLINE STORE": "Catering available. Merchandise also for sale!",
  "OTHER": "Gift certificates available.",
  "EMAIL CONTACT": "nateswingsandwaffles@gmail.com"
},
{
  "restaurant": "Quick Pack Food Mart (Fried Chicken)",
  "neighborhood": "Central District",
  "address": "325 Martin Luther King Jr Way S, Seattle, WA 98144",
  "lat": "47.599597",
  "long": "-122.29784",
  "service": "Takeout",
  "contact": "(206) 328-2127",
  "website": "https://www.yelp.com/biz/quick-pack-food-mart-seattle",
  "EMAIL CONTACT": "TBD"
},
{
  "restaurant": "Taste of the Caribbean",
  "neighborhood": "Central District",
  "address": "1212 E Jefferson St, Seattle, WA 98122",
  "lat": "47.60647",
  "long": "-122.316",
  "service": "Takeout, Delivery",
  "contact": "(206) 323-9112",
  "website": "http://www.tasteofthecaribbeanseattle.com/",
  "MERCH/ONLINE STORE": "Catering available.",
  "OTHER": "More hush-puppies! YES.",
  "EMAIL CONTACT": "tasteofthecaribbean.206@gmail.com"
},
{
  "restaurant": "The Fish Box",
  "neighborhood": "Central District",
  "address": "172 20th Ave, Seattle, WA 98122",
  "lat": "47.603304",
  "long": "-122.30596",
  "service": "Takeout, Delivery",
  "contact": "(206) 227-1911",
  "website": "http://thefishbox.net/",
  "MERCH/ONLINE STORE": "Catering available."
},
{
  "restaurant": "East African Imports",
  "neighborhood": "Central District",
  "address": "306 23rd Ave S, Seattle, WA 98144",
  "lat": "47.600057",
  "long": "-122.30199",
  "service": "Takeout",
  "contact": "(206) 322-7717",
  "website": "https://eastafricanimports.com/",
  "MERCH/ONLINE STORE": "Order food and also maintains a marketplace of spices, sauces, and more. Wholesale available.",
  "EMAIL CONTACT": "info@eastafricanimports.com"
},
{
  "restaurant": "Joyce's Market and Cafe",
  "neighborhood": "Central District",
  "address": "2717 E Union St, Seattle, WA 98122",
  "lat": "47.612789",
  "long": "-122.29656",
  "service": "Takeout",
  "contact": "(206) 322-9140",
  "website": "https://www.instagram.com/joycesmarketandcafe/",
  "MERCH/ONLINE STORE": "Meals, pastries, meats, cheeses, etc for sale!",
  "EMAIL CONTACT": "cheeseplattersandmore@gmail.com"
},
{
  "restaurant": "Zagol Ethiopian Restaurant",
  "neighborhood": "Central District",
  "address": "2722 E Cherry St, Seattle, WA 98122",
  "lat": "47.608114",
  "long": "-122.29665",
  "service": "Takeout",
  "contact": "(206) 322-1019",
  "website": "http://www.zagolethiopianrestaurant.weebly.com/1",
  "EMAIL CONTACT": "TBD"
},
{
  "restaurant": "Ras Dashen",
  "neighborhood": "Central District",
  "address": "2801 E Cherry St, Seattle, WA 98122",
  "lat": "47.607772",
  "long": "-122.29561",
  "service": "Takeout",
  "contact": "(206) 709-7626",
  "website": "https://rasdashenseattle.com/",
  "EMAIL CONTACT": "mabera@msn.com"
},
{
  "restaurant": "Blue Nile Ethiopian Restaurant",
  "neighborhood": "Central District",
  "address": "464 12th Ave, Seattle, WA 98122",
  "lat": "47.605987",
  "long": "-122.31647",
  "service": "Takeout",
  "contact": "(206) 320-8501",
  "website": "http://www.bluenilerestaurant.com/",
  "EMAIL CONTACT": "TBD"
},
{
  "restaurant": "Safari Njema",
  "neighborhood": "Columbia City",
  "address": "5041 Rainier Ave S, Seattle, WA 98118",
  "lat": "47.555985",
  "long": "-122.28409",
  "service": "Takeout",
  "contact": "(206) 723-3058",
  "website": "https://safari-restaurant.business.site/",
  "EMAIL CONTACT": "TBD"
},
{
  "restaurant": "Cafe Avole",
  "neighborhood": "Columbia City",
  "address": "6630 Rainier Ave S #3350, Seattle, WA 98118",
  "lat": "47.542582",
  "long": "-122.27266",
  "service": "Takeout",
  "contact": "(206) 472-4096",
  "website": "https://www.facebook.com/cafeavole/",
  "EMAIL CONTACT": "avolecoffee@gmail.com"
},
{
  "restaurant": "Island Soul Rum Bar & Soul Shack",
  "neighborhood": "Columbia City",
  "address": "4869 Rainier Ave S, Seattle, WA 98118",
  "lat": "47.558114",
  "long": "-122.28543",
  "service": "Takeout, Delivery",
  "contact": "206) 329-1202",
  "website": "https://www.islandsoulrestaurant.com/",
  "MERCH/ONLINE STORE": "Catering available.",
  "EMAIL CONTACT": "info@islandsoulrestaurant.com"
},
{
  "restaurant": "Emma’s BBQ",
  "neighborhood": "Columbia City",
  "address": "5310-5300 Rainier Ave S, Seattle, WA 98118",
  "lat": "47.554006",
  "long": "-122.28033",
  "service": "Takeout, Delivery",
  "contact": "(206) 413-1523",
  "website": "https://www.facebook.com/emmasbbq1/",
  "EMAIL CONTACT": "Emmasbbq1@gmail.com"
},
{
  "restaurant": "Kezira Cafe",
  "neighborhood": "Columbia City",
  "address": "5014 39th Ave S, Seattle, WA 98118",
  "lat": "47.556366",
  "long": "-122.28294",
  "service": "Takeout",
  "contact": "(206) 588-1024",
  "website": "keziracaffe.com",
  "EMAIL CONTACT": "kezirac@gmail.com"
},
{
  "restaurant": "Bana Ethiopian and Eritrean Restaurant",
  "neighborhood": "Columbia City",
  "address": "4423 Rainier Ave S, Seattle, WA 98118",
  "lat": "47.56356",
  "long": "-122.28825",
  "service": "Takeout",
  "contact": "206-723-3587",
  "website": "https://banaethiopiantogo.com/",
  "EMAIL CONTACT": "TBD"
},
{
  "restaurant": "Bananas Grill",
  "neighborhood": "Columbia City",
  "address": "4520 Martin Luther King Jr Way S, Seattle, WA 98108",
  "lat": "47.562597",
  "long": "-122.29377",
  "service": "Takeout, Delivery",
  "contact": "(206) 420-4839",
  "website": "https://bananagrillseattle.com/",
  "MERCH/ONLINE STORE": "Catering available.",
  "EMAIL CONTACT": "bananasgrillseattle@gmail.com"
},
{
  "restaurant": "Cafe Ibex",
  "neighborhood": "Columbia City",
  "address": "3219 Martin Luther King Jr Way S, Seattle, WA 98144",
  "lat": "47.574603",
  "long": "-122.29761",
  "service": "Takeout, Delivery",
  "contact": "(206) 721-7537",
  "website": "http://cafeibexseattle.cafecityguide.website/",
  "OTHER": "Beer growlers available too.",
  "EMAIL CONTACT": "TBD"
},
{
  "restaurant": "Lil Red Takeout & Catering",
  "neighborhood": "Columbia City",
  "address": "4225 Rainier Ave S, Seattle, WA 98118",
  "lat": "47.564917",
  "long": "-122.28887",
  "service": "Takeout, Delivery",
  "contact": "(206) 760 2931",
  "website": "https://lilredtakeout.com/",
  "MERCH/ONLINE STORE": "Catering available.",
  "EMAIL CONTACT": "bigredej@yahoo.com"
},
{
  "restaurant": "Emerald City Fish and Chips",
  "neighborhood": "Columbia City",
  "address": "3756 Rainier Ave S, Seattle, WA 98144",
  "lat": "47.570023",
  "long": "-122.29063",
  "service": "Takeout, Delivery",
  "contact": "(206) 760-3474",
  "website": "https://www.emeraldcityfishchips.com/",
  "EMAIL CONTACT": "emeraldcityfishco@gmail.com"
},
{
  "restaurant": "Delish Ethiopean Cuisine",
  "neighborhood": "Columbia City",
  "address": "South, 5701 Rainier Ave, Seattle, WA 98118",
  "lat": "47.540246",
  "long": "-122.26855",
  "service": "Takeout, Delivery",
  "contact": "(206) 723-3821",
  "website": "http://delishethiopianfood.com/",
  "MERCH/ONLINE STORE": "Catering available.",
  "EMAIL CONTACT": "delish86@gmail.com"
},
{
  "restaurant": "Clockwork Counter Bakery",
  "neighborhood": "Columbia City",
  "address": "4100 Rainier Ave S, Seattle, WA 98118",
  "lat": "47.565937",
  "long": "-122.28828",
  "service": "Takeout",
  "contact": "(206) 941-6267",
  "website": "https://www.facebook.com/clockworkcounterbakery/",
  "EMAIL CONTACT": "clockworkcounter@mail.com"
},
{
  "restaurant": "Comfort Zone",
  "neighborhood": "Columbia City",
  "address": "5016 Rainier Ave S, Seattle, WA 98118",
  "lat": "47.556551",
  "long": "-122.28378",
  "service": "Takeout, Delivery",
  "contact": "(206) 246-2800",
  "website": "https://thecomfortzonesoulfood.com/",
  "EMAIL CONTACT": "hello@thecomfortzonesoulfood.com"
},
{
  "restaurant": "City Teriyaki",
  "neighborhood": "Columbia City",
  "address": "5400 Rainier Ave S, Seattle, WA 98118",
  "lat": "47.553268",
  "long": "-122.27892",
  "service": "Takeout, Delivery",
  "contact": "(206) 723-2489",
  "website": "https://cityteriyaki.com/",
  "OTHER": "Good vegan options.",
  "EMAIL CONTACT": "info@cityteriyaki.com"
},
{
  "restaurant": "Hunni Co.",
  "neighborhood": "Edmonds",
  "address": "186 Sunset Ave, Edmonds, WA 98020",
  "lat": "47.810152",
  "long": "-122.3834",
  "service": "Takeout, Delivery",
  "contact": "425-582-0671",
  "website": "https://www.hunniwater.com/info",
  "OTHER": "Specialty beverages!",
  "EMAIL CONTACT": "info@hunniwater.com"
},
{
  "restaurant": "Grandma's in Da Kitchen",
  "neighborhood": "Everett",
  "address": "2831 W Marine View Dr, Everett, WA 98201",
  "lat": "47.97957",
  "long": "-122.21399",
  "service": "Takeout, Delivery",
  "contact": "(253) 426-5618",
  "website": "https://www.facebook.com/grandmasindakitchen/",
  "EMAIL CONTACT": "grandmasindakitchen@gmail.com"
},
{
  "restaurant": "Heaven Sent Fried Chicken",
  "neighborhood": "Everett + Lake City",
  "address": "615 112th St SE suite e, Everett, WA 98208",
  "lat": "47.896866",
  "long": "-122.22357",
  "service": "Takeout, Delivery",
  "contact": "425-267-9672",
  "website": "https://www.heavensentfriedchicken.com/",
  "OTHER": "Cute kids section on their website with activity guides!",
  "EMAIL CONTACT": "TBD"
},
{
  "restaurant": "Lumpia World",
  "neighborhood": "Federal Way",
  "address": "1610 S 341st Pl, Federal Way, WA 98003",
  "lat": "47.296187",
  "long": "-122.31282",
  "service": "Takeout, Delivery",
  "contact": "(253) 874-5867",
  "website": "http://www.lumpiaworld.com/",
  "MERCH/ONLINE STORE": "Meal prep, frozen meals, and catering available. Also gift cards!",
  "EMAIL CONTACT": "info@lumpiaworld.com"
},
{
  "restaurant": "Cakes of Paradise",
  "neighborhood": "Georgetown",
  "address": "6322 6th Ave S, Seattle, WA 98108",
  "lat": "47.545534",
  "long": "-122.32585",
  "service": "Takeout",
  "contact": "206) 763-1151",
  "website": "http://www.cakesofparadisebakery.com/",
  "MERCH/ONLINE STORE": "Desserts and drinks, specialty bakery",
  "EMAIL CONTACT": "orders@cakesofparadisebakery.com"
},
{
  "restaurant": "We Eat Conscious",
  "neighborhood": "Georgetown",
  "address": "5606 6th Ave S, Seattle, WA 98108",
  "lat": "47.552429",
  "long": "-122.32642",
  "service": "Takeout",
  "contact": "(206) 659-4098",
  "website": "http://consciouseatery.org/",
  "OTHER": "Catering available.",
  "EMAIL CONTACT": "info@consciouseatery.org"
},
{
  "restaurant": "Mojito",
  "neighborhood": "Greenlake",
  "address": "7545 Lake City Way NE, Seattle, WA 98115",
  "lat": "47.684485",
  "long": "-122.31602",
  "service": "Takeout, Delivery",
  "contact": "(206) 525-3162",
  "website": "https://www.mojitoseattle.com/",
  "EMAIL CONTACT": "info@mojitoseattle.com"
},
{
  "restaurant": "Altha's Louisiana Cajun Store & Deli",
  "neighborhood": "Kent",
  "address": "201 E Meeker St, Kent, WA 98032",
  "lat": "47.381773",
  "long": "-122.23216",
  "service": "Takeout",
  "contact": "(253) 719-2242",
  "website": "https://althascajunspices.com/",
  "MERCH/ONLINE STORE": "Order food and also maintains a marketplace of spices, sauces, meat, and more.",
  "EMAIL CONTACT": "TBD"
},
{
  "restaurant": "Nana's Southern Kitchen",
  "neighborhood": "Kent",
  "address": "10234 SE 256th St, Kent, WA 98030",
  "lat": "47.372778",
  "long": "-122.20455",
  "service": "Takeout",
  "contact": "(253) 243-6711",
  "website": "https://www.facebook.com/nanassouthernkitchen/",
  "EMAIL CONTACT": "nanasouthernkitchen@gmail.com"
},
{
  "restaurant": "Dat Creole Soul",
  "neighborhood": "Kent",
  "address": "24050 Pacific Hwy S, Kent, WA 98032, USA",
  "lat": "47.385504",
  "long": "-122.29435",
  "service": "Takeout",
  "contact": "(206) 379-1513",
  "website": "https://datcreolesoul.com/",
  "MERCH/ONLINE STORE": "Food truck!",
  "OTHER": "Registered non-profit! Donates time and food to the community!",
  "EMAIL CONTACT": "info@datcreolesoul.com"
},
{
  "restaurant": "KJs Cakery Bakery Sweet Shop",
  "neighborhood": "Kent",
  "address": "204 Central Ave N #102, Kent, WA 98032",
  "lat": "47.382596",
  "long": "-122.2306",
  "service": "Takeout",
  "contact": "(253) 277-2516",
  "website": "https://www.kjscakerybakery.com/",
  "OTHER": "Bakery and sweet spot! Catering, events, and classes.",
  "EMAIL CONTACT": "kathyjo@kjscakerybakery.com"
},
{
  "restaurant": "Pinckney Cookies",
  "neighborhood": "Kirkland",
  "address": "11251 120th Ave NE #110, Kirkland, WA 98033",
  "lat": "47.701403",
  "long": "-122.18148",
  "service": "Delivery",
  "contact": "(425) 283-9993",
  "website": "lovethesecookies.com",
  "MERCH/ONLINE STORE": "Great gifts! Ships cookies and gift baskets throughout the US",
  "EMAIL CONTACT": "inquiry@pinckneycookiecafe.com"
},
{
  "restaurant": "Enat Ethiopian Restaurant",
  "neighborhood": "Lake City",
  "address": "11546 15th Ave NE, Seattle, WA 98125",
  "lat": "47.713652",
  "long": "-122.3121",
  "service": "Takeout",
  "contact": "(206) 362-4901",
  "website": "http://www.ethiopianrestaurant.com/washington/enat_ethiopia.html",
  "EMAIL CONTACT": "esouk@hotmail.com"
},
{
  "restaurant": "Ahadu Restaurant",
  "neighborhood": "Lake City",
  "address": "1508 NE 117th St, Seattle, WA 98125",
  "lat": "47.714158",
  "long": "-122.31204",
  "service": "Takeout",
  "contact": "(206) 440-3399",
  "website": "https://www.facebook.com/myahadu/",
  "EMAIL CONTACT": "contact@myahadu.com"
},
{
  "restaurant": "Zuri's Donutz",
  "neighborhood": "Lynnwood",
  "address": "7600 196th St SW, Lynnwood, WA 98036",
  "lat": "47.821132",
  "long": "-122.33662",
  "service": "Takeout, Delivery",
  "contact": "(425) 582-8803",
  "website": "https://www.facebook.com/zurisdonutz/",
  "OTHER": "DONUTS. Enough said! Get some!",
  "EMAIL CONTACT": "zurisdonutz@gmail.com"
},
{
  "restaurant": "Scoop Du Jour",
  "neighborhood": "Madison",
  "address": "4029 E Madison St, Seattle, WA 98112",
  "lat": "47.633874",
  "long": "-122.28033",
  "service": "Takeout",
  "contact": "(206) 325-9562",
  "website": "https://www.facebook.com/pages/Scoop-Du-Jour-Ice-Creamery/111578165543941",
  "EMAIL CONTACT": "TBD"
},
{
  "restaurant": "Kaffa Coffee and Wine Bar",
  "neighborhood": "New Holly",
  "address": "8136 Rainier Ave S, Seattle, WA 98118",
  "lat": "47.529876",
  "long": "-122.26971",
  "service": "Takeout",
  "contact": "(206) 453-3558",
  "website": "https://kaffafoods.com/",
  "MERCH/ONLINE STORE": "Coffee, wine, grocery items (including specialty spices) available at their website.",
  "EMAIL CONTACT": "kaffaseattle@gmail.com"
},
{
  "restaurant": "Jebena Cafe",
  "neighborhood": "Northgate",
  "address": "1510 NE 117th St, Seattle, WA 98125",
  "lat": "47.714153",
  "long": "-122.31194",
  "service": "Takeout, Delivery",
  "contact": "(206) 365-0757",
  "website": "https://jebenacafe.com/",
  "MERCH/ONLINE STORE": "Has market that carries products with all Ethiopian essentials (coffee & teaware, spices & lentils for Ethiopian cooking, coffee incense)",
  "EMAIL CONTACT": "jebenamarket@gmail.com"
},
{
  "restaurant": "Drae's Lake Route",
  "neighborhood": "Rainier Valley",
  "address": "9261 57th Ave S, Seattle, WA 98118",
  "lat": "47.519811",
  "long": "-122.26177",
  "service": "Takeout, Delivery",
  "contact": "(206) 722-9464",
  "website": "https://www.facebook.com/Draeslakeroute/",
  "EMAIL CONTACT": "Sharronthestylist@gmail.com"
},
{
  "restaurant": "Umami Kushi",
  "neighborhood": "Rainier Valley",
  "address": "9099 Seward Park Ave S, Seattle, WA 98118",
  "lat": "47.520438",
  "long": "-122.2633",
  "service": "Takeout, Delivery",
  "contact": "(206) 265-1923",
  "website": "https://umamikushi.com/",
  "MERCH/ONLINE STORE": "Catering available.",
  "EMAIL CONTACT": "umamikushi@icloud.com"
},
{
  "restaurant": "Mama Sambusa Kitchen",
  "neighborhood": "Rainier Valley",
  "address": "8300 Rainier Ave S, Seattle, WA 98118",
  "lat": "47.528966",
  "long": "-122.26977",
  "service": "Takeout",
  "contact": "(206) 356-2911",
  "website": "instagram.com/mamasambusakitchen/",
  "OTHER": "Cafe that serves take out from 4pm - 4am!",
  "EMAIL CONTACT": "TBD"
},
{
  "restaurant": "Junebaby",
  "neighborhood": "Ravenna",
  "address": "2122 NE 65th St, Seattle, WA 98115",
  "lat": "47.675909",
  "long": "-122.3041",
  "service": "Takeout",
  "contact": "(206) 257-4470",
  "website": "https://www.junebabyseattle.com/welcome",
  "MERCH/ONLINE STORE": "Yes - check out their website.",
  "EMAIL CONTACT": "info@junebabyseattle.com"
},
{
  "restaurant": "Lucinda",
  "neighborhood": "Ravenna",
  "address": "2120 NE 65th St, Seattle, WA 98115",
  "lat": "47.675905",
  "long": "-122.3042",
  "service": "Takeout",
  "contact": "(206) 457-8180",
  "website": "https://www.lucindaseattle.com/",
  "EMAIL CONTACT": "info@lucindaseattle.com"
},
{
  "restaurant": "Salare",
  "neighborhood": "Ravenna",
  "address": "2404 NE 65th St, Seattle, WA 98115",
  "lat": "47.675947",
  "long": "-122.30122",
  "service": "Takeout",
  "contact": "(206) 556-2192",
  "website": "https://salarerestaurant.com/",
  "EMAIL CONTACT": "info@salarerestaurant.com"
},
{
  "restaurant": "Boon Boona",
  "neighborhood": "Renton",
  "address": "724 S 3rd St, Renton, WA 98057",
  "lat": "47.4798",
  "long": "-122.20712",
  "service": "Takeout",
  "contact": "(425) 496-8618",
  "website": "https://www.boonboonacoffee.com/",
  "MERCH/ONLINE STORE": "https://www.boonboonacoffee.com/coffee",
  "EMAIL CONTACT": "info@boonboonacoffee.com"
},
{
  "restaurant": "Juba",
  "neighborhood": "Renton",
  "address": "14223 Tukwila International Blvd, Tukwila, WA 98168",
  "lat": "47.475846",
  "long": "-122.28383",
  "service": "Takeout",
  "contact": "(206) 242-2011",
  "website": "https://juba-restaurant-cafe.business.site/",
  "MERCH/ONLINE STORE": "Yes - check out their website.",
  "EMAIL CONTACT": "hello@jubacafe.com"
},
{
  "restaurant": "The Wine Alley",
  "neighborhood": "Renton",
  "address": "14276 SE 176th St, Renton, WA 98058",
  "lat": "47.445403",
  "long": "-122.14938",
  "service": "Takeout",
  "contact": "(425) 271-4501",
  "website": "https://www.thewinealley.com/The_Wine_Alley2/About_Us.html",
  "MERCH/ONLINE STORE": "Wine shop with meals!",
  "OTHER": "Wine club too.",
  "EMAIL CONTACT": "info@thewinealley.com"
},
{
  "restaurant": "Angel City Deli",
  "neighborhood": "Skway",
  "address": "12621 Renton Ave S, Seattle, WA 98178",
  "lat": "47.490605",
  "long": "-122.23988",
  "service": "Takeout",
  "contact": "(206) 772-2223",
  "website": "https://www.angelcitydeli.com/",
  "EMAIL CONTACT": "angelcitydeli@mail.com"
},
{
  "restaurant": "Catfish Corner",
  "neighborhood": "Skyway",
  "address": "11805 Renton Ave S, Seattle, WA 98178",
  "lat": "47.496854",
  "long": "-122.24747",
  "service": "Takeout",
  "contact": "(206) 735-7084",
  "website": "https://www.catfish-corner.com/",
  "OTHER": "Hush-puppies! YES.",
  "EMAIL CONTACT": "terrelljackson2010@gmail.com"
},
{
  "restaurant": "Silver Slice Bakery",
  "neighborhood": "Sodo",
  "address": "4634 E Marginal Way S, Seattle, WA 98134",
  "lat": "47.561208",
  "long": "-122.33872",
  "contact": "(206) 802-8666",
  "website": "https://www.silverslicebakery.com/",
  "OTHER": "Gluten free bakery.",
  "EMAIL CONTACT": "sales@silverslicebakery.com"
},
{
  "restaurant": "Where Ya At Matt",
  "neighborhood": "Various Locations - Greenwood most recently!",
  "address": "656 NW 85th St, Seattle, WA 98117",
  "lat": "47.69088",
  "long": "-122.36577",
  "service": "Takeout",
  "contact": "(314) 374-3081",
  "website": "https://whereyaatmatt.com/",
  "type": "Food truck",
  "EMAIL CONTACT": "info@whereyaatmatt.com"
},
{
  "restaurant": "Gravy Vashon",
  "neighborhood": "Vashon",
  "address": "17629 Vashon Hwy SW, Vashon, WA 98070",
  "lat": "47.446543",
  "long": "-122.46079",
  "service": "Takeout",
  "contact": "(206) 463-0489",
  "website": "https://www.gravyvashon.com/#gravy",
  "MERCH/ONLINE STORE": "Catering available.",
  "EMAIL CONTACT": "pepa@gravyvashon.com"
},
{
  "restaurant": "Pam's Kitchen",
  "neighborhood": "Wallingford + South Lake Union",
  "address": "1715 N 45th St, Seattle, WA 98103",
  "lat": "47.661156",
  "long": "-122.33663",
  "service": "Takeout",
  "contact": "(206) 696-7010",
  "website": "https://pams-kitchen.com/home-2/",
  "MERCH/ONLINE STORE": "Email for catering needs.",
  "EMAIL CONTACT": "pamskitchen@gmail.com"
},
{
  "restaurant": "Black Star Kebab Food Truck",
  "neighborhood": "Wedgwood - Food Truck! Various locations)",
  "address": "7751 63rd Ave NE, Seattle, WA 98115",
  "lat": "47.686915",
  "long": "-122.26329",
  "service": "Takeout",
  "contact": "206-499-4019",
  "website": "http://www.blackstarkebab.com/",
  "type": "Food truck",
  "OTHER": "Track the food truck here: https://www.facebook.com/blackstarkebabs/",
  "EMAIL CONTACT": "info@blackstarkebab.com"
},
{
  "restaurant": "Jones Barbeque",
  "neighborhood": "West Seattle",
  "address": "4417 Fauntleroy Way SW, Seattle, WA 98126",
  "lat": "47.564299",
  "long": "-122.37771",
  "service": "Takeout, Delivery",
  "contact": "(206) 739-6169",
  "website": "https://www.jonesbarbeque.com/",
  "OTHER": "10000000 people recommend this joint!",
  "EMAIL CONTACT": "jonesbarbeque1@gmail.com"
},
{
  "restaurant": "Jemil's Big Easy",
  "neighborhood": "West Seattle",
  "address": "5604, Seattle, WA 98106",
  "lat": "47.544034",
  "long": "-122.34987",
  "service": "Takeout",
  "contact": "(206) 641-6551",
  "website": "https://jemilsbigeasy.com/"
}]

function initMap() {
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 13,
    center: new google.maps.LatLng(47.608013, -122.3321),
    mapTypeId: google.maps.MapTypeId.ROADMAP,
  })

  var infoWindow = new google.maps.InfoWindow({})

  for (var data of jsondata) {
    // var data = jsondata[i];
    var marker = new google.maps.Marker({
      position: new google.maps.LatLng(data.lat, data.long),
      map: map,
    })

    google.maps.event.addListener(
      marker,
      'click',
      (function (marker) {
        var directions = 'https://www.google.com/maps/dir/?api=1&destination='+data.lat+','+data.long;
        var contentString = '<strong>' + data.restaurant + '</strong><br><a target="_blank" rel="noopener noreferrer" href="' + directions + '">'+ data.address + '</a><br>'+data.contact+'<br>Offerings: '+data.service+'<br><a target="_blank" rel="noopener noreferrer" href="' + data.website + '">' + data.website.toString() + '</a>'
        return function () {
          infoWindow.setContent(contentString)
          infoWindow.open(map, marker)
        }
      })(marker)
    )
  }
}